import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next | TS | Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen justify-center items-center">
        <div className="max-w-xl rounded overflow-hidden shadow-lg my-2">
          <img
            className="w-full"
            src="https://picsum.photos/576/432"
            alt="Lorem Picsum"
          />
          <div className="px-6 py-4">
            <div className="font-bold text-xl mb-2">Next + Tailwind + Ts</div>
            <p className="text-grey-darker text-base">
              This is a template app for Next, Tailwind, and Typescript.
              Slap whatever you want in here you sly gamers.
            </p>
          </div>
        </div>
      </div>

    </div>
  )
}

export default Home
